In [1]:
import numpy as np

In [3]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a2=np.arange(12,dtype=float)
a2


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [7]:
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [9]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(12,)
(2, 2, 2)


In [10]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


Array operations


In [16]:
b1=np.arange(12).reshape(3,4)
b2=np.arange(12,24).reshape(3,4)
b1
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

arithematic operation

In [13]:
print(b1+b2)
print(b1-b2)
print(b1*b2)
print(b1/b2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


relational operations

In [17]:
print(b1>b2)#false
print(b1<b2)#true
print(b1>=b2)#false
print(b1<=b2)#true
print(b1==b2)#false
print(b1!=b2)#true

[[False False False False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [31]:
import random
c1=np.random.random((3,3))
c1=np.round(c1*10)
print(c1)


[[10. 10.  1.]
 [ 8.  2.  6.]
 [ 1.  3.  1.]]


In [33]:
np.max(c1)

10.0

In [34]:
np.min(c1)

1.0

1:row
0:column

In [37]:
np.max(c1,axis=0)

array([10., 10.,  6.])

In [40]:
d1=np.arange(10)
d1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
d2=np.arange(12).reshape(3,4)
d2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
d2[1,2]
d2[0,0]

0

In [48]:
d3=np.arange(8).reshape(2,2,2)
d3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [52]:
print(d3[0,1,1])
d3[1,1,1]

3


7

In [54]:
d3=np.arange(16).reshape(2,4,2)
d3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [55]:
d3[1,2,1]

13